import React, { useEffect, useState, useCallback } from 'react';
import type { CustomerReport, TaskReport, BillingReport, SummaryReport } from '../types/reporting';
import { reportingApi } from '../api/reportingApi';
import {
  CustomersIcon,
  TasksIcon,
  BillingIcon,
  RefreshIcon,
} from '../components/common/Icons';
import { Button } from '../components/common/Button';
import { Card } from '../components/common/Card';
import { LoadingSpinner } from '../components/common/LoadingSpinner';
import { ErrorMessage } from '../components/common/ErrorMessage';

export const ReportsPage: React.FC = () => {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [summary, setSummary] = useState<SummaryReport | null>(null);
  const [customerStat, setCustomerStat] = useState<CustomerReport | null>(null);
  const [taskStat, setTaskStat] = useState<TaskReport | null>(null);
  const [billingStat, setBillingStat] = useState<BillingReport | null>(null);

  const [lastRefreshed, setLastRefreshed] = useState<Date | null>(null);

  const loadReports = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      // Execute reporting API calls
      const [sumRes, custRes, taskRes, billRes] = await Promise.all([
        reportingApi.getSummaryReport(),
        reportingApi.getCustomerReport(),
        reportingApi.getTaskReport(),
        reportingApi.getBillingReport(),
      ]);

      setSummary(sumRes);
      setCustomerStat(custRes);
      setTaskStat(taskRes);
      setBillingStat(billRes);
      setLastRefreshed(new Date());
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Failed to retrieve operational reports';
      setError(msg);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadReports();
  }, [loadReports]);

  return (
    <>
      <div className="page-header">
        <div>
          <h2 className="page-title">Operational Reports & Aggregates</h2>
          <p className="page-description">
            Read-only statistics generated by Noah Taylor's Reporting API (Analytics Team)
          </p>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          {lastRefreshed && (
            <span style={{ fontSize: 12, color: 'var(--text-secondary)' }}>
              Updated: {lastRefreshed.toLocaleTimeString()}
            </span>
          )}
          <Button
            variant="secondary"
            size="sm"
            icon={<RefreshIcon size={14} />}
            onClick={loadReports}
            disabled={loading}
          >
            Refresh Reports
          </Button>
        </div>
      </div>

      {error && (
        <ErrorMessage
          message={error}
          onRetry={loadReports}
        />
      )}

      {loading ? (
        <LoadingSpinner message="Aggregating metrics from upstream APIs via Reporting API..." />
      ) : (
        <>
          {/* Executive Summary Card */}
          <Card title="Overall Operational Summary (/reports/summary)">
            <p style={{ fontSize: 14, color: 'var(--text-secondary)', marginBottom: 16 }}>
              The Reporting API synthesizes live metrics from the Customer, Task, and Billing APIs over HTTP without requiring a separate database.
            </p>

            <div className="metrics-grid">
              <div className="stat-card" style={{ borderLeft: '4px solid #3b82f6' }}>
                <div className="stat-card-top">
                  <span className="stat-label">Total Registered Customers</span>
                  <div className="stat-icon">
                    <CustomersIcon size={20} />
                  </div>
                </div>
                <div className="stat-value">{summary?.customers ?? '—'}</div>
                <div className="stat-subtext">Upstream: Customer API</div>
              </div>

              <div className="stat-card" style={{ borderLeft: '4px solid #f59e0b' }}>
                <div className="stat-card-top">
                  <span className="stat-label">Total Open Tasks</span>
                  <div className="stat-icon" style={{ color: 'var(--warning)', backgroundColor: 'var(--warning-light)' }}>
                    <TasksIcon size={20} />
                  </div>
                </div>
                <div className="stat-value">{summary?.open_tasks ?? '—'}</div>
                <div className="stat-subtext">Tasks in TODO or IN_PROGRESS state</div>
              </div>

              <div className="stat-card" style={{ borderLeft: '4px solid #10b981' }}>
                <div className="stat-card-top">
                  <span className="stat-label">Pending Invoices</span>
                  <div className="stat-icon" style={{ color: 'var(--info)', backgroundColor: 'var(--info-light)' }}>
                    <BillingIcon size={20} />
                  </div>
                </div>
                <div className="stat-value">{summary?.pending_invoices ?? '—'}</div>
                <div className="stat-subtext">Invoices in PENDING payment state</div>
              </div>
            </div>
          </Card>

          {/* Detailed Endpoint Breakdown */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 24 }}>
            <Card title="Customer Service Metrics (/reports/customers)">
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                <div className="detail-grid">
                  <span className="detail-label">Endpoint</span>
                  <code style={{ fontSize: 12, backgroundColor: '#f1f5f9', padding: '2px 6px', borderRadius: 4 }}>
                    GET /reports/customers
                  </code>

                  <span className="detail-label">Metric</span>
                  <span className="detail-value">customers</span>

                  <span className="detail-label">Current Value</span>
                  <span className="detail-value" style={{ fontWeight: 700, fontSize: 18, color: 'var(--primary)' }}>
                    {customerStat?.customers ?? '—'}
                  </span>
                </div>
              </div>
            </Card>

            <Card title="Task Service Metrics (/reports/tasks)">
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                <div className="detail-grid">
                  <span className="detail-label">Endpoint</span>
                  <code style={{ fontSize: 12, backgroundColor: '#f1f5f9', padding: '2px 6px', borderRadius: 4 }}>
                    GET /reports/tasks
                  </code>

                  <span className="detail-label">Metric</span>
                  <span className="detail-value">open_tasks</span>

                  <span className="detail-label">Current Value</span>
                  <span className="detail-value" style={{ fontWeight: 700, fontSize: 18, color: 'var(--warning)' }}>
                    {taskStat?.open_tasks ?? '—'}
                  </span>
                </div>
              </div>
            </Card>

            <Card title="Billing Service Metrics (/reports/billing)">
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                <div className="detail-grid">
                  <span className="detail-label">Endpoint</span>
                  <code style={{ fontSize: 12, backgroundColor: '#f1f5f9', padding: '2px 6px', borderRadius: 4 }}>
                    GET /reports/billing
                  </code>

                  <span className="detail-label">Metric</span>
                  <span className="detail-value">pending_invoices</span>

                  <span className="detail-label">Current Value</span>
                  <span className="detail-value" style={{ fontWeight: 700, fontSize: 18, color: 'var(--info)' }}>
                    {billingStat?.pending_invoices ?? '—'}
                  </span>
                </div>
              </div>
            </Card>
          </div>

        </>
      )}
    </>
  );
};
