name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**/*.md'

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  deployment-guard:
    name: Deployment Guard
    uses: SparrowX-ECS/workflows-templates/.github/workflows/deployment-guard.yaml@v5.1.0
    with:
      env-params-file: ecs-parameters-dev.yaml
      environment: dev

  pre-build:
    name: Pre-Build
    needs: deployment-guard
    if: needs.deployment-guard.outputs.deployment-enabled == 'true'
    uses: SparrowX-ECS/workflows-templates/.github/workflows/pre-build.yaml@v5.1.0
    with:
      env-params-file: ecs-parameters-dev.yaml

  build:
    name: Build
    needs: pre-build
    if: needs.pre-build.outputs.build-needed == 'true'
    uses: SparrowX-ECS/workflows-templates/.github/workflows/build.yaml@v5.1.0
    with:
      env-params-file: ecs-parameters-dev.yaml
      frontend: true
      authoritative-build: true

  image-security-scan:
    name: Image Security Scan
    needs: build
    uses: SparrowX-ECS/workflows-templates/.github/workflows/image-security-scan.yaml@v5.1.0
    with:
      env-params-file: ecs-parameters-dev.yaml
      image-tag: ${{ needs.build.outputs.image-tag }}

  ci-quality-gate:
    name: CI Quality Gate
    needs: image-security-scan
    uses: SparrowX-ECS/workflows-templates/.github/workflows/ci-quality-gate.yaml@v5.1.0
    with:
      image-security-artifact: ${{ needs.image-security-scan.outputs.artifact-name }}
      security-policy-file: app-sec-policy.yaml

  sign-image:
    name: Sign Image
    needs:
      - ci-quality-gate
      - build
    uses: SparrowX-ECS/workflows-templates/.github/workflows/sign-image.yaml@v5.1.0
    with:
      env-params-file: ecs-parameters-dev.yaml
      image-tag: ${{ needs.build.outputs.image-tag }}

  #Publish Image metadata only if ci quality gate is passed
  publish-image-metadata:
    name: Publish Image Metadata
    needs:
      - sign-image
      - build
    if: needs.sign-image.outputs.status == 'passed'
    uses: SparrowX-ECS/workflows-templates/.github/workflows/publish-image-metadata.yaml@v5.1.0
    with:
      ssm-parameter-path: ${{ vars.DEV_DEPLOYED_PARAM_STORE_PATH }}
      env-params-file: ecs-parameters-dev.yaml
      image-tag: ${{ needs.build.outputs.image-tag }}
      image-uri: ${{ needs.sign-image.outputs.image-uri }}
