name: Web Portal CI/CD

on:
  pull_request:
    branches:
      - main
    paths:
        - 'src/**'
        - 'Dockerfile'
        - 'ecs-parameters.yaml'
        - '.github/workflows/deploy.yaml'

  push:
    branches:
      - main
    paths:
        - 'src/**'
        - 'Dockerfile'
        - 'ecs-parameters.yaml'
        - '.github/workflows/deploy.yaml'

permissions:
  contents: read

env:
  AWS_REGION: eu-west-1

jobs:
  changes:
    uses: SparrowX-ECS/workflows-templates/.github/workflows/changes.yaml@v1.0.2

  test:
    needs: changes
    if: needs.changes.outputs.code == 'true'
    uses: SparrowX-ECS/workflows-templates/.github/workflows/test.yaml@v1.0.2
    with:
      runtime: node

  build:
    name: Build
    needs: [changes, test]
    if: |
      needs.changes.outputs.code == 'true' &&
      needs.test.result == 'success' &&
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    uses: SparrowX-ECS/workflows-templates/.github/workflows/build.yaml@v1.0.2
    with:
      frontend: true


  deploy:
    name: Deploy
    needs: [changes, test, build]
    if: |
      always() &&
      needs.changes.outputs.deploy == 'true' &&
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      (needs.test.result == 'success' || needs.test.result == 'skipped') &&
      (needs.build.result == 'success' || needs.build.result == 'skipped')
    uses: SparrowX-ECS/workflows-templates/.github/workflows/deploy.yaml@v1.0.2
    with:
      database-enabled: false
      update-image: ${{ needs.changes.outputs.code == 'true' }}