name: Automated Deployment to Development

on:
  push:
    branches:
      - main
    paths:
          - 'src/**'
          - 'tests/**'
          - 'Dockerfile'
          - 'ecs-parameters-dev.yaml'
          - '.github/workflows/deploy-dev.yaml'
          
permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  resolve-image:
    name: Resolve Candidate Image
    uses: SparrowX-ECS/workflows-templates/.github/workflows/resolve-image.yaml@v4.4.0
    with:
      ssm-parameter-path: ${{ vars.DEV_DEPLOYED_PARAM_STORE_PATH }}
      env-params-file: ecs-parameters-dev.yaml

  deploy:
    name: Deploy to Development
    needs: resolve-image
    uses: SparrowX-ECS/workflows-templates/.github/workflows/deploy.yaml@v4.4.0
    with:
      environment: dev
      database-enabled: false
      env-params-file: ecs-parameters-dev.yaml
      image-tag: ${{ needs.resolve-image.outputs.image-tag }}


  # Run smoke tests against the deployed service.
  smoke-test:
    name: Smoke Test Development
    needs: deploy
    uses: SparrowX-ECS/workflows-templates/.github/workflows/smoke-test.yaml@v4.4.0
    with:
      env-params-file: ecs-parameters-dev.yaml
      base-url: ${{ vars.DEV_BASE_URL }}
      timeout: '120'

  
  #Add DAST Job Here, To Scan Application in RunTime for Vulnerabilities, For Better Security Measures

  # Publish Image metadata only if deployment and smoke tests are successful
  # Image will be marked as candidate for promotion to production
  publish-image-metadata:
    name: Publish Image Metadata
    needs: [smoke-test, resolve-image]
    uses: SparrowX-ECS/workflows-templates/.github/workflows/publish-image-metadata.yaml@v4.4.0
    with:
      ssm-parameter-path: ${{ vars.PROD_CANDIDATE_PARAM_STORE_PATH }}
      env-params-file: ecs-parameters-dev.yaml
      image-tag: ${{ needs.resolve-image.outputs.image-tag }}