name: Manual Re-Deploy

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: Type REDEPLOY to confirm ECS Task Redeployment
        required: true
        type: string


permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-1
    
jobs:
  redeploy:
    uses: SparrowX-ECS/workflows-templates/.github/workflows/deploy.yaml@v1.0.2
    with:
      database-enabled: false
      update-image: false
      job-name: Re-Deploy